CC = gcc
INCLUDE = "C:\Users\svyut\vcpkg\installed\x64-windows\include"
LIB = "C:\Users\svyut\vcpkg\installed\x64-windows\lib"
DLL = "C:\Users\svyut\vcpkg\installed\x64-windows\bin"
CFLAGS = -I$(INCLUDE) -L$(LIB) -lssh2 -lws2_32  -lcrypto -g -Wall
PROGRAM = mysftp
OBJS = mysftp.c

all: $(PROGRAM)
$(PROGRAM): $(OBJS)
			$(CC) $(CFLAGS) -o $(PROGRAM) $(OBJS)


